name: Build and test app

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build: 
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@master
    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
    - uses: actions/cache@v2
      with:
        path: |
          %userprofile%\.nuget\packages
        key: ${{ runner.os }}-nuget-build-v2-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget-build-v2-
    - name: Restore packages
      run: dotnet restore --use-lock-file -s https://api.nuget.org/v3/index.json
    - name: Build with dotnet
      run: dotnet build --configuration Release
  test:
    runs-on: windows-latest
    needs: build
    steps:
    - uses: actions/checkout@master
    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
    - uses: actions/cache@v2
      id: cache-packages
      with:
        path: |
          %userprofile%\.nuget\packages
        key: ${{ runner.os }}-nuget-v2-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget-v2-
    - name: Restore packages
      if: steps.cache-packages.outputs.cache-hit != 'true'
      run: dotnet restore --use-lock-file -s https://api.nuget.org/v3/index.json
    - name: Unit tests
      run: echo Tests should be here
  deploy-to-azure:
    runs-on: windows-latest
    needs: publish
    steps:
    - uses: actions/checkout@master
    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
    - uses: actions/cache@v2
      id: cache-packages
      with:
        path: |
          %userprofile%\.nuget\packages
        key: ${{ runner.os }}-nuget-v2-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget-v2-
    - name: Restore packages
      if: steps.cache-packages.outputs.cache-hit != 'true'
      run: dotnet restore --use-lock-file -s https://api.nuget.org/v3/index.json
    - name: Publish solution
      run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp
    - name: Deploy to Azure
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'Schoodule'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_c8d74799c0d0468d8456fa0ce984a341 }}
        package: ${{env.DOTNET_ROOT}}/myapp