name: Deploy ASP.Net Core app to Azure Web App - Schoodule

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy-to-azure:
    runs-on: windows-latest
    needs: publish
    steps:
    - name: Publish solution
      run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp
    - name: Deploy to Azure
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'Schoodule'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_c8d74799c0d0468d8456fa0ce984a341 }}
        package: ${{env.DOTNET_ROOT}}/myapp