# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - Schoodule

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@master

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'

    - uses: actions/cache@v2
      with:
        path: |
          ~/.nuget/packages
          %userprofile%\.nuget\packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget-

    - name: Restore packages
      run: dotnet restore --use-lock-file -s https://api.nuget.org/v3/index.json

    - name: Build with dotnet
      run: dotnet build --configuration Release

    - name: Unit tests
      run: echo Tests should be here

    - name: dotnet publish
      run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'Schoodule'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_c8d74799c0d0468d8456fa0ce984a341 }}
        package: ${{env.DOTNET_ROOT}}/myapp 

    - name: Login to Azure
      uses: Azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }} 

    - name: Get connection string
      uses: Azure/get-keyvault-secrets@v1
      with: 
        keyvault: "SchooduleKeys"
        secrets: 'ConnectionString'
      id: secrets

    - name: Update database
      run: |
        dotnet tool install --global dotnet-ef
        dotnet tool restore
        dotnet ef database update -p ./Schoodule.DataAccess -s ./Schoodule.API --connection "${{ steps.secrets.outputs.ConnectionString }}"