name: Test app Schoodule

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build: 
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@master

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'

    - uses: actions/cache@v2
      with:
        path: |
          ~/.nuget/packages
          %userprofile%\.nuget\packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget-

    - name: Restore packages
      run: dotnet restore --use-lock-file -s https://api.nuget.org/v3/index.json

    - name: Build with dotnet
      run: dotnet build --configuration Release

  test:
    runs-on: windows-latest
    needs: build

    steps:
    - name: Unit tests
      run: echo Tests should be here

  publish:
    runs-on: windows-latest
    needs: test

    steps:
    - name: Publish solution
      run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp